# Generated by Django 5.0.6 on 2025-11-14 07:06

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('models_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_image', models.ImageField(blank=True, null=True, upload_to='results/')),
                ('square_meters', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('materials', models.TextField()),
                ('timeline', models.CharField(max_length=120)),
                ('recommendations', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mock_payload', models.JSONField(blank=True, default=dict)),
                ('construction_model', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_result', to='models_core.constructionmodel')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
